package com.osamu.aide.engine.gradle

import java.io.File

/**
 * What the editor needs from a Gradle project -- its source folders and its
 * compile classpath -- written by the build and read back by the app.
 *
 * **A build script is a program, so only Gradle can say what it resolves to.**
 * A dependency is `implementation(libs.androidx.core.ktx)` from a version
 * catalog, or comes from a convention plugin in `build-logic`, or is a
 * `project(":core")` whose own dependencies are `api`. Reading the text gets
 * none of that right. So every Gradle build this engine runs carries an init
 * script that asks AGP for each debug variant's `compileClasspath` -- AARs
 * already transformed into jars, other modules' outputs, everything javac saw --
 * and writes the list into the module's own `build/aide/`. The editor reads it
 * after the build. Before the first build there is nothing to read, which is
 * the same honest state `R` is in.
 *
 * Writer and reader live here together because the file's name and format are
 * a private agreement between them.
 */
object GradleEditorInputs {

    private const val CLASSPATH_FILE = "compile-classpath-debug.txt"

    private val BUILD_FILES = setOf("build.gradle.kts", "build.gradle")

    /** Not project source, and not worth walking. */
    private val SKIPPED = setOf("build", ".gradle", ".git", ".idea", "node_modules")

    /**
     * The init script, in Groovy for the reason `GradleDebugAgent` gives.
     *
     * Registered as a task that `assembleDebug` depends on, with the classpath
     * as its declared input, rather than resolved during configuration: that
     * would force every AAR transform before Gradle has decided whether
     * anything needs building, and resolving at configuration is exactly what
     * Gradle warns about. Library modules too, since their sources are open in
     * the same editor.
     */
    internal val INIT_SCRIPT = """
        // Generated by AIDE-OS. Records each module's debug compile classpath in
        // build/aide/ for the editor; changes nothing in the project.
        def aideRecordClasspath = { project ->
            def components = project.extensions.getByName('androidComponents')
            components.onVariants(components.selector().withBuildType('debug')) { variant ->
                def classpath = variant.compileClasspath
                def output = project.layout.buildDirectory.file('aide/$CLASSPATH_FILE')
                def record = project.tasks.register('aideRecordClasspath' + variant.name.capitalize()) { task ->
                    task.inputs.files(classpath)
                    task.outputs.file(output)
                    task.doLast {
                        def file = output.get().asFile
                        file.parentFile.mkdirs()
                        file.text = classpath.files.collect { it.absolutePath }.join('\n')
                    }
                }
                project.tasks.matching { it.name == 'assemble' + variant.name.capitalize() }
                    .configureEach { it.dependsOn(record) }
            }
        }
        allprojects {
            pluginManager.withPlugin('com.android.application') { aideRecordClasspath(project) }
            pluginManager.withPlugin('com.android.library') { aideRecordClasspath(project) }
        }
    """.trimIndent() + "\n"

    /** Writes the init script into [dir] and returns it. */
    fun writeInitScript(dir: File): File {
        dir.mkdirs()
        return File(dir, "aide-editor.init.gradle").apply { writeText(INIT_SCRIPT) }
    }

    /**
     * Every module's `src/main/java` and `src/main/kotlin`.
     *
     * Found by walking rather than read from `settings.gradle`, for the
     * build-script reason above; a stray module folder that is not included
     * costs a few extra source files on the path, which is harmless.
     */
    fun sourceRoots(root: File): List<File> =
        root.walkTopDown()
            .maxDepth(MAX_DEPTH)
            .onEnter { it == root || (it.name !in SKIPPED && !it.name.startsWith(".")) }
            .filter {
                it.isDirectory && (it.name == "java" || it.name == "kotlin") &&
                    it.parentFile?.name == "main" && it.parentFile?.parentFile?.name == "src"
            }
            .sortedBy { it.invariantSeparatorsPath }
            .toList()

    /**
     * The jars the last debug build compiled against, and each module's `R`.
     *
     * **The project's own outputs are left out** -- another module's classes
     * jar, say -- because its sources are already on the source path, and a
     * class that is both source and binary is ambiguous to the Kotlin session
     * and stale to javac the moment the source is edited. `R` is the exception:
     * it has no source anywhere, and AGP writes it as a jar.
     */
    fun classpath(root: File): List<File> {
        // Compared canonically: Gradle records `/storage/emulated/0/...` for a
        // project the app knows as `/sdcard/...`, and the same directory under
        // two spellings would not be recognised as the project's own.
        val canonicalRoot = root.canonicalFile
        // Each module's build directory, found from its build file without
        // entering any build/: a walk that did would read every intermediate
        // AGP wrote, thousands of files in a project of any size, to find a few.
        val buildDirs = root.walkTopDown()
            .maxDepth(MAX_DEPTH)
            .onEnter { it == root || (it.name !in SKIPPED && !it.name.startsWith(".")) }
            .filter { it.isFile && it.name in BUILD_FILES }
            .mapNotNull { it.parentFile }
            .plus(root)
            .distinct()
            .map { File(it, "build") }
            .filter { it.isDirectory }
            .toList()

        val recorded = buildDirs
            .map { File(it, "aide/$CLASSPATH_FILE") }
            .filter { it.isFile }
            .flatMap { it.readLines() }
            .filter { it.isNotBlank() }
            .map(::File)
            .filter { it.exists() && !it.canonicalFile.startsWith(canonicalRoot) }

        val rJars = buildDirs.flatMap { build ->
            R_JAR_DIRS.map { File(build, "intermediates/$it/debug") }
                .filter { it.isDirectory }
                .flatMap { dir -> dir.walkTopDown().filter { it.isFile && it.name == "R.jar" }.toList() }
        }
        return (recorded + rJars).distinct()
    }

    /** Where AGP 8 and 9 put a module's `R` jar, for an application and for a library. */
    private val R_JAR_DIRS = listOf(
        "compile_and_runtime_not_namespaced_r_class_jar",
        "compile_and_runtime_r_class_jar",
        "compile_r_class_jar",
    )

    private const val MAX_DEPTH = 8
}
