package com.osamu.aide.engine.gradle

import com.osamu.aide.engine.api.DebugAgentSource
import com.osamu.aide.engine.api.DebuggerRequest
import java.io.File
import java.util.zip.ZipFile

/**
 * Puts the debugger's agent into an app the project's own Gradle builds.
 *
 * The fast engine writes the agent beside `R.java` and into a manifest it
 * merged itself. Here the build is not ours, so the agent goes in the one way
 * that leaves the project untouched: an **init script** named on the command
 * line. It finds each application module as AGP is applied and adds, to its
 * debug variants only, a source directory holding the agent and a manifest
 * holding its declarations -- through AGP's variant API, so its own merger
 * places them and resolves the package with `${applicationId}`.
 *
 * Nothing is written into the project for the same reason the SDK tool path is
 * passed as a property rather than into `gradle.properties`: the project is the
 * user's, and usually a git checkout. The files live under the engine's own
 * Gradle home and are rewritten for each debug build.
 *
 * **The APK is checked afterwards, because the hook can do nothing quietly.**
 * A plugin older than the variant API this uses, or an app module that is not
 * `com.android.application`, builds successfully without the agent -- and the
 * session would then wait for a port that never opens. [carriesAgent] turns
 * that into a sentence.
 */
internal object GradleDebugAgent {

    /** Writes the agent, its manifest and the init script; returns the script. */
    fun prepare(workDir: File, request: DebuggerRequest): File {
        workDir.deleteRecursively()
        val sources = File(workDir, "java")
        File(sources, DebugAgentSource.relativePath).apply {
            parentFile?.mkdirs()
            writeText(DebugAgentSource.javaSource(request))
        }
        val manifest = File(workDir, "AndroidManifest.xml").apply {
            writeText(DebugAgentSource.manifestOverlay(request))
        }
        return File(workDir, "aide-debug.init.gradle").apply {
            writeText(initScript(sources, manifest))
        }
    }

    /**
     * The init script, in Groovy so it needs no Kotlin DSL compile -- which on
     * a phone is tens of seconds before the build has started.
     *
     * `withBuildType("debug")` rather than every variant: a release variant
     * built in the same invocation must not carry a listening socket.
     * `withPlugin` rather than `afterEvaluate`, because variant callbacks must
     * be registered before AGP computes the variants, which it does in its own
     * `afterEvaluate`.
     */
    internal fun initScript(sources: File, manifest: File): String = """
        // Generated by AIDE-OS for one debug build. Adds the debugger's agent to
        // debug variants of application modules; changes nothing in the project.
        def agentSources = ${sources.absolutePath.groovyQuoted()}
        def agentManifest = ${manifest.absolutePath.groovyQuoted()}
        allprojects {
            pluginManager.withPlugin('com.android.application') {
                def components = extensions.getByName('androidComponents')
                components.onVariants(components.selector().withBuildType('debug')) { variant ->
                    variant.sources.java.addStaticSourceDirectory(agentSources)
                    variant.sources.manifests.addStaticManifestFile(agentManifest)
                }
            }
        }
    """.trimIndent() + "\n"

    /**
     * Whether a built APK has the agent in its dex.
     *
     * A string search: a class's descriptor is in the dex string table
     * verbatim, and the question is only whether the source was compiled and
     * packaged.
     */
    fun carriesAgent(apk: File): Boolean = runCatching {
        val descriptor = "L" + DebuggerRequest.AGENT_CLASS.replace('.', '/') + ";"
        ZipFile(apk).use { zip ->
            zip.entries().asSequence()
                .filter { it.name.startsWith("classes") && it.name.endsWith(".dex") }
                .any { entry ->
                    String(zip.getInputStream(entry).use { it.readBytes() }, Charsets.ISO_8859_1)
                        .contains(descriptor)
                }
        }
    }.getOrDefault(false)

    private fun String.groovyQuoted(): String = "'" + replace("\\", "\\\\").replace("'", "\\'") + "'"
}
