package com.osamu.aide.engine.fast

import org.w3c.dom.Document
import org.w3c.dom.Element
import java.io.File
import javax.xml.parsers.DocumentBuilderFactory
import javax.xml.transform.TransformerFactory
import javax.xml.transform.dom.DOMSource
import javax.xml.transform.stream.StreamResult

/**
 * Makes a built app debuggable *by us*, by putting a JDWP listener inside it.
 *
 * Spike R15 established that an unprivileged app cannot attach to another
 * app's JDWP -- but that ART ships OpenJDK's `libjdwp.so`, and any debuggable
 * process may attach it to *itself* and listen on a socket. So the debuggee
 * half of the debugger is not a permission AIDE-OS asks for; it is four lines
 * that this puts into the app it builds. `tools/jdwp/FINDINGS.md`.
 *
 * Two things go into the APK, and both are reverted by simply not asking:
 *
 *  - **A generated `ContentProvider`**, because providers are created before
 *    `Application.onCreate` and before any activity, so the port is open by the
 *    time there is anything to stop. The alternative -- generating an
 *    `Application` subclass -- would silently replace the user's own, and a
 *    project that has one is exactly the project complex enough to be worth
 *    debugging. `androidx.startup` uses this trick for the same reason; see
 *    [ManifestMerger].
 *  - **`android.permission.INTERNET`**, because `dt_socket` is the only
 *    transport ART's agent has, so the JDWP server is a TCP listener. Without
 *    it the agent calls `exit(2)` from a stdout nobody reads and the app
 *    vanishes at startup with no exception and no tombstone.
 *
 * **Never in a release build, and never unasked.** This adds a permission the
 * user did not write and opens a port on their app; doing it to every debug
 * build because it is convenient would be a decision taken on their behalf.
 * [BuildRequest.debugPort] is null unless something asked, and a release build
 * refuses it outright.
 */
internal object DebugAgent {

    /** The package the generated provider lands in. */
    private const val PACKAGE = "aide.debug"

    /** The class name, which the manifest entry has to match exactly. */
    private const val CLASS = "AideDebugAgent"

    private const val ANDROID_NAMESPACE = "http://schemas.android.com/apk/res/android"
    private const val INTERNET = "android.permission.INTERNET"

    /**
     * The API level `Debug.attachJvmtiAgent` arrived at.
     *
     * The generated code checks this at runtime rather than the build refusing:
     * a project may legitimately declare a lower `minSdk` and still be debugged
     * on a device new enough. Below it the provider does nothing and says so,
     * which is a debugger that will not attach -- not an app that will not run.
     */
    private const val JVMTI_ATTACH_SDK = 28

    /**
     * Writes the agent's source into [workspace] and its declarations into
     * [manifest].
     *
     * Returns the generated file, which the caller does not need to add to the
     * compiler's inputs: it is written into `generated/java`, which
     * [BuildWorkspace.generatedJavaSources] already sweeps for `R.java`.
     */
    fun install(workspace: BuildWorkspace, manifest: File, applicationId: String, port: Int): File {
        val source = File(workspace.generatedJava, "${PACKAGE.replace('.', '/')}/$CLASS.java")
        source.parentFile?.mkdirs()
        source.writeText(providerSource(port))
        declare(manifest, applicationId)
        return source
    }

    private fun providerSource(port: Int): String = """
        package $PACKAGE;

        /**
         * Opens a JDWP port so AIDE-OS can debug this app.
         *
         * Generated by the build; not part of this project's source. It exists
         * only in a debug build that was asked for a debugger, and a release
         * build never contains it.
         */
        public final class $CLASS extends android.content.ContentProvider {

            private static final String TAG = "AideDebugAgent";

            @Override
            public boolean onCreate() {
                if (android.os.Build.VERSION.SDK_INT < $JVMTI_ATTACH_SDK) {
                    android.util.Log.w(TAG, "this device is too old to attach a debugger");
                    return true;
                }
                try {
                    android.os.Debug.attachJvmtiAgent(
                        "libjdwp.so",
                        "transport=dt_socket,server=y,suspend=n,address=127.0.0.1:$port",
                        null);
                    android.util.Log.i(TAG, "debugger listening on 127.0.0.1:$port");
                } catch (Throwable t) {
                    // Never fatal. A debugger that cannot start is a missing
                    // feature; an app that will not launch is a broken build.
                    android.util.Log.w(TAG, "could not start the debugger", t);
                }
                return true;
            }

            @Override
            public android.database.Cursor query(android.net.Uri uri, String[] projection,
                    String selection, String[] selectionArgs, String sortOrder) {
                return null;
            }

            @Override
            public String getType(android.net.Uri uri) {
                return null;
            }

            @Override
            public android.net.Uri insert(android.net.Uri uri, android.content.ContentValues values) {
                return null;
            }

            @Override
            public int delete(android.net.Uri uri, String selection, String[] selectionArgs) {
                return 0;
            }

            @Override
            public int update(android.net.Uri uri, android.content.ContentValues values,
                    String selection, String[] selectionArgs) {
                return 0;
            }
        }
    """.trimIndent()

    /**
     * Adds the provider and the permission to an already-merged manifest.
     *
     * Idempotent by name, because a rebuild reuses the workspace and a second
     * `<provider>` with the same authority makes the *install* fail rather than
     * the build.
     */
    private fun declare(manifest: File, applicationId: String) {
        val factory = DocumentBuilderFactory.newInstance().apply { isNamespaceAware = true }
        val document = factory.newDocumentBuilder().parse(manifest)
        val root = document.documentElement

        if (!root.hasPermission(INTERNET)) {
            root.insertBefore(
                document.createElement("uses-permission").apply {
                    setAttributeNS(ANDROID_NAMESPACE, "android:name", INTERNET)
                },
                root.firstChild,
            )
        }

        val application = document.getElementsByTagName("application").item(0) as? Element
            ?: throw IllegalStateException(
                "this project's manifest has no <application>, so there is nowhere " +
                    "to put the debugger",
            )
        val name = "$PACKAGE.$CLASS"
        if (application.childElements().none {
                it.tagName == "provider" &&
                    it.getAttributeNS(ANDROID_NAMESPACE, "name") == name
            }
        ) {
            application.appendChild(
                document.createElement("provider").apply {
                    setAttributeNS(ANDROID_NAMESPACE, "android:name", name)
                    // Namespaced by applicationId: an authority is unique
                    // across the whole device, and two apps built here with the
                    // same literal would refuse to install alongside each other.
                    setAttributeNS(
                        ANDROID_NAMESPACE,
                        "android:authorities",
                        "$applicationId.aide-debug-agent",
                    )
                    setAttributeNS(ANDROID_NAMESPACE, "android:exported", "false")
                },
            )
        }

        TransformerFactory.newInstance().newTransformer()
            .transform(DOMSource(document), StreamResult(manifest))
    }

    private fun Element.hasPermission(permission: String): Boolean =
        childElements().any {
            it.tagName == "uses-permission" &&
                it.getAttributeNS(ANDROID_NAMESPACE, "name") == permission
        }

    private fun Element.childElements(): List<Element> =
        (0 until childNodes.length).mapNotNull { childNodes.item(it) as? Element }
}
