package com.osamu.aide.engine.api

/**
 * The debugger's half that lives inside the app: its Java source, and what its
 * manifest has to declare.
 *
 * Here rather than in either engine because both put it into an app. The fast
 * engine compiles the source beside `R.java` and writes the declarations into
 * the manifest it merged itself; the Gradle engine hands both to the project's
 * own build through an init script. One source keeps the two apps identical to
 * the debugger, which talks to the agent by field name and cannot tell who
 * built it. Plain text, so this module still knows nothing of a toolchain.
 *
 * `debugger/FINDINGS.md` holds the reasons behind every line of the agent.
 */
object DebugAgentSource {

    private val PACKAGE = DebuggerRequest.AGENT_CLASS.substringBeforeLast('.')
    private val CLASS = DebuggerRequest.AGENT_CLASS.substringAfterLast('.')

    /** Where the source goes under a source root: `aide/debug/AideDebugAgent.java`. */
    val relativePath: String = "${PACKAGE.replace('.', '/')}/$CLASS.java"

    /**
     * The API level `Debug.attachJvmtiAgent` arrived at.
     *
     * The generated code checks this at runtime rather than the build refusing:
     * a project may legitimately declare a lower `minSdk` and still be debugged
     * on a device new enough. Below it the provider does nothing and says so,
     * which is a debugger that will not attach -- not an app that will not run.
     */
    private const val JVMTI_ATTACH_SDK = 28

    const val INTERNET = "android.permission.INTERNET"

    /** The agent, a `ContentProvider`, listening on [DebuggerRequest.port]. */
    fun javaSource(request: DebuggerRequest): String {
        val authority = request.handshakeAuthority?.let { "\"" + it.javaEscaped() + "\"" } ?: "null"
        return """
        package $PACKAGE;

        /**
         * Opens a JDWP port so AIDE-OS can debug this app.
         *
         * Generated by the build; not part of this project's source. It exists
         * only in a debug build that was asked for a debugger, and a release
         * build never contains it.
         */
        public final class $CLASS extends android.content.ContentProvider {

            private static final String TAG = "AideDebugAgent";

            // Assigned in a static block so it is not a compile-time constant:
            // as one, ECJ proves the null check below dead and reports it, and
            // that warning lands in the Problems pane of a project that never
            // wrote this file.
            private static final String HANDSHAKE_AUTHORITY;
            static {
                HANDSHAKE_AUTHORITY = $authority;
            }

            /**
             * Set to true by the debugger once its breakpoints are in place.
             *
             * Written over JDWP, which is why it is a static field and not a
             * method: the debugger can set a field in a running VM without the
             * app having to call anything.
             */
            public static volatile boolean ${DebuggerRequest.RELEASE_FIELD};

            /** Set by the debugger when a breakpoint is hit; see holdIfExpected. */
            public static volatile boolean ${DebuggerRequest.COME_FORWARD_FIELD};

            @Override
            public boolean onCreate() {
                if (android.os.Build.VERSION.SDK_INT < $JVMTI_ATTACH_SDK) {
                    android.util.Log.w(TAG, "this device is too old to attach a debugger");
                    return true;
                }
                try {
                    android.os.Debug.attachJvmtiAgent(
                        "libjdwp.so",
                        "transport=dt_socket,server=y,suspend=n,address=127.0.0.1:${request.port}",
                        null);
                    android.util.Log.i(TAG, "debugger listening on 127.0.0.1:${request.port}");
                } catch (Throwable t) {
                    // Never fatal. A debugger that cannot start is a missing
                    // feature; an app that will not launch is a broken build.
                    android.util.Log.w(TAG, "could not start the debugger", t);
                    return true;
                }
                holdIfExpected();
                return true;
            }

            /**
             * Waits for the debugger, but only if the IDE says one is coming.
             *
             * Providers are created before Application.onCreate and before any
             * activity, so holding here is what lets a breakpoint in onCreate
             * be placed before onCreate runs. An app launched any other way --
             * from the launcher, long after the IDE session -- is not expected
             * and does not wait at all.
             */
            private void holdIfExpected() {
                if (HANDSHAKE_AUTHORITY == null) return;
                boolean expected = false;
                android.os.Bundle answer = null;
                try {
                    answer = getContext().getContentResolver().call(
                            android.net.Uri.parse("content://" + HANDSHAKE_AUTHORITY),
                            "${DebuggerRequest.HANDSHAKE_METHOD}",
                            getContext().getPackageName(),
                            null);
                    expected = answer != null && answer.getBoolean("${DebuggerRequest.HANDSHAKE_EXPECTED}");
                } catch (Throwable t) {
                    // The IDE is not installed, not running, or not answering:
                    // nobody is coming, so do not wait for anybody.
                }
                if (!expected) return;
                keepTheIdeAwake(answer.getString("${DebuggerRequest.HANDSHAKE_IDE_SERVICE}"));
                android.util.Log.i(TAG, "waiting for the debugger to place its breakpoints");
                long deadline = android.os.SystemClock.uptimeMillis() + ${DebuggerRequest.STARTUP_HOLD_MS};
                while (!${DebuggerRequest.RELEASE_FIELD} && android.os.SystemClock.uptimeMillis() < deadline) {
                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException e) {
                        return;
                    }
                }
                android.util.Log.i(TAG, ${DebuggerRequest.RELEASE_FIELD}
                        ? "released by the debugger"
                        : "the debugger did not arrive; starting anyway");
            }

            /**
             * Binds the IDE, and hands the screen back to it on request.
             *
             * The binding keeps the IDE from being frozen while this app is in
             * front -- a frozen IDE never resumes a thread it holds. The
             * thread brings the IDE forward when the debugger asks, because
             * this app is the one on screen and so the one allowed to.
             */
            private void keepTheIdeAwake(String flattened) {
                if (flattened == null) return;
                final android.content.ComponentName ide =
                        android.content.ComponentName.unflattenFromString(flattened);
                if (ide == null) return;
                final android.content.Context context = getContext().getApplicationContext();
                try {
                    context.bindService(
                            new android.content.Intent().setComponent(ide),
                            new android.content.ServiceConnection() {
                                @Override
                                public void onServiceConnected(android.content.ComponentName name, android.os.IBinder service) {
                                }

                                @Override
                                public void onServiceDisconnected(android.content.ComponentName name) {
                                }
                            },
                            android.content.Context.BIND_AUTO_CREATE);
                } catch (Throwable t) {
                    android.util.Log.w(TAG, "could not bind the IDE; it may be frozen while this app is in front", t);
                }
                Thread forward = new Thread(new Runnable() {
                    @Override
                    public void run() {
                        while (true) {
                            if (${DebuggerRequest.COME_FORWARD_FIELD}) {
                                ${DebuggerRequest.COME_FORWARD_FIELD} = false;
                                android.content.Intent launch = context.getPackageManager()
                                        .getLaunchIntentForPackage(ide.getPackageName());
                                if (launch != null) {
                                    launch.addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK
                                            | android.content.Intent.FLAG_ACTIVITY_RESET_TASK_IF_NEEDED);
                                    try {
                                        context.startActivity(launch);
                                    } catch (Throwable t) {
                                        android.util.Log.w(TAG, "could not bring the IDE forward", t);
                                    }
                                }
                            }
                            try {
                                Thread.sleep(100);
                            } catch (InterruptedException e) {
                                return;
                            }
                        }
                    }
                }, "aide-debug-forward");
                forward.setDaemon(true);
                forward.start();
            }

            @Override
            public android.database.Cursor query(android.net.Uri uri, String[] projection,
                    String selection, String[] selectionArgs, String sortOrder) {
                return null;
            }

            @Override
            public String getType(android.net.Uri uri) {
                return null;
            }

            @Override
            public android.net.Uri insert(android.net.Uri uri, android.content.ContentValues values) {
                return null;
            }

            @Override
            public int delete(android.net.Uri uri, String selection, String[] selectionArgs) {
                return 0;
            }

            @Override
            public int update(android.net.Uri uri, android.content.ContentValues values,
                    String selection, String[] selectionArgs) {
                return 0;
            }
        }
        """.trimIndent()
    }

    /**
     * The agent's declarations as a manifest of their own, for a build whose
     * manifest merger does the rest -- AGP's.
     *
     * The authority uses AGP's `${applicationId}` placeholder rather than a
     * name written here, because the package a Gradle build produces is its own
     * business: a debug `applicationIdSuffix` makes it something the IDE's
     * record of the project does not say. See [DebuggerRequest.agentAuthority]
     * for why the authority is namespaced at all, and the fast engine's
     * `DebugAgent.declare` for why `<queries>` is not optional.
     */
    fun manifestOverlay(request: DebuggerRequest): String = buildString {
        appendLine("""<?xml version="1.0" encoding="utf-8"?>""")
        appendLine("<!-- Generated by AIDE-OS for one debug build; not part of this project. -->")
        appendLine("""<manifest xmlns:android="http://schemas.android.com/apk/res/android">""")
        appendLine("""    <uses-permission android:name="$INTERNET" />""")
        request.handshakeAuthority?.let {
            appendLine("    <queries>")
            appendLine("""        <provider android:authorities="${it.xmlEscaped()}" />""")
            appendLine("    </queries>")
        }
        appendLine("    <application>")
        appendLine("        <provider")
        appendLine("""            android:name="${DebuggerRequest.AGENT_CLASS}"""")
        appendLine("""            android:authorities="${DebuggerRequest.agentAuthority(APPLICATION_ID_PLACEHOLDER)}"""")
        appendLine("""            android:exported="true" />""")
        appendLine("    </application>")
        appendLine("</manifest>")
    }

    /** AGP's manifest placeholder for the package the build produces. */
    const val APPLICATION_ID_PLACEHOLDER = "\${applicationId}"

    private fun String.javaEscaped(): String = replace("\\", "\\\\").replace("\"", "\\\"")

    private fun String.xmlEscaped(): String =
        replace("&", "&amp;").replace("\"", "&quot;").replace("<", "&lt;")
}
